[tool.poetry]
name = "epstein-text-messages-2"
version = "0.1.0"
description = ""
authors = ["ashariyar <ashariyar@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
rich = "^14.2.0"
python-dotenv = "^1.2.1"
bpython = "^0.26"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
